#!/bin/bash

Color='\033[0;33m'
NoColor='\033[0m'

./install || exit 1

screen -dmS playmouth.preview -L -Logfile daemon.log plymouthd --debug --no-daemon --tty=`tty`
sleep 1

echo -e "${Color}plymouth://process/show ${NoColor}"
plymouth --show-splash
./test
sleep 1

echo -e "${Color}plymouth://process/hide ${NoColor}"
plymouth --hide-splash
plymouth --quit || killall plymouthd || true
echo -e "${Color}plymouth://done ${NoColor}"
