#!/bin/sh

# first check that we are in an appropriate runlevel rlevel=$(runlevel | cut -d " " -f 2) if [[ "$rlevel" != "2" && "$rlevel" != "3" ]] then echo "ERROR: You must be at runlevel 2 or 3" exit 1 fi

echo "plymouth://process/testing"

echo " start"

sleep 1 && \
    plymouth --ping && \
    plymouth --show-splash && \
    sleep 3 && \
    plymouth --quit && \
echo "plymouth://done"

# sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/darwin/darwin.plymouth 100
# sudo update-alternatives --config default.plymouth
# sudo update-initramfs -u
# plymouthd --no-daemon --debug
