#!/bin/bash

Color='\033[0;33m'
NoColor='\033[0m'

echo -e "${Color}plymouth://process/changemode --type boot-up ${NoColor}"
sudo plymouth change-mode --boot-up
sleep 10

echo -e "${Color}plymouth://process/changemode --type system-upgrade ${NoColor}"
sudo plymouth change-mode --system-upgrade
sleep 1
echo -e "${Color}plymouth://process/update/system ${NoColor}"
sudo plymouth system-update --progress 0
sleep 1
sudo plymouth system-update --progress 20
sleep 1
sudo plymouth system-update --progress 30
sleep 1
sudo plymouth system-update --progress 40
sleep 1
sudo plymouth system-update --progress 50
sleep 1
sudo plymouth system-update --progress 60
sleep 1
sudo plymouth system-update --progress 70
sleep 1
sudo plymouth system-update --progress 80
sleep 1
sudo plymouth system-update --progress 90
sleep 1
sudo plymouth system-update --progress 100
sleep 2

for i in {1..10}
do
    sudo plymouth --update=test$i
    sleep 2
done

echo -e "${Color}plymouth://process/hide ${NoColor}"
sudo plymouth quit --retain-splash
sleep 1

exit 0

# sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/darwin/darwin.plymouth 100
# sudo update-alternatives --config default.plymouth
# sudo update-initramfs -u
# plymouthd --no-daemon --debug

# `Transition` config in `two-step` animation piece code from https://gitlab.freedesktop.org/plymouth/plymouth
#  if (strcmp (transition, "fade-over") == 0)
#        plugin->transition = PLY_PROGRESS_ANIMATION_TRANSITION_FADE_OVER;
#    else if (strcmp (transition, "cross-fade") == 0)
#        plugin->transition = PLY_PROGRESS_ANIMATION_TRANSITION_CROSS_FADE;
#    else if (strcmp (transition, "merge-fade") == 0)
#        plugin->transition = PLY_PROGRESS_ANIMATION_TRANSITION_MERGE_FADE;

#Font=Ubuntu 24
#TitleFont=Ubuntu Light 30
