#!/bin/bash

Color='\033[0;33m'
NoColor='\033[0m'

# test disk scan
for i in {1..10}
do
    plymouth --update=fsck:sda1:$(($i * 10))
    sleep 0.3
done

#plymouth ask-for-password --prompt "filesystem encrypted" --dont-pause-progress

#for i in {1..10}
#do
#    sudo plymouth --update=test:$(($i * 10))
#    sleep 1
#done


#for i in {1..10}
#do
#    sudo plymouth --update=event:$i
#    sleep 1
#done

./test.disk

exit 0

# sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/darwin/darwin.plymouth 100
# sudo update-alternatives --config default.plymouth
# sudo update-initramfs -u
# plymouthd --no-daemon --debug

# `Transition` config in `two-step` animation piece code from https://gitlab.freedesktop.org/plymouth/plymouth
#  if (strcmp (transition, "fade-over") == 0)
#        plugin->transition = PLY_PROGRESS_ANIMATION_TRANSITION_FADE_OVER;
#    else if (strcmp (transition, "cross-fade") == 0)
#        plugin->transition = PLY_PROGRESS_ANIMATION_TRANSITION_CROSS_FADE;
#    else if (strcmp (transition, "merge-fade") == 0)
#        plugin->transition = PLY_PROGRESS_ANIMATION_TRANSITION_MERGE_FADE;

#Font=Ubuntu 24
#TitleFont=Ubuntu Light 30
